In [4]:
url="https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data"

"https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data"

In [6]:
using Knet

In [7]:
@doc download

```
download(url::AbstractString, [localfile::AbstractString])
```

Download a file from the given url, optionally renaming it to the given local file name. Note that this function relies on the availability of external tools such as `curl`, `wget` or `fetch` to download the file and is provided for convenience. For production use or situations in which more options are needed, please use a package that provides the desired functionality instead.


In [8]:
data=readdlm(download(url))

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 49082  100 49082    0     0  91518      0 --:--:-- --:--:-- --:--:-- 91570


506×14 Array{Float64,2}:
 0.00632  18.0   2.31  0.0  0.538  6.575  …  296.0  15.3  396.9    4.98  24.0
 0.02731   0.0   7.07  0.0  0.469  6.421     242.0  17.8  396.9    9.14  21.6
 0.02729   0.0   7.07  0.0  0.469  7.185     242.0  17.8  392.83   4.03  34.7
 0.03237   0.0   2.18  0.0  0.458  6.998     222.0  18.7  394.63   2.94  33.4
 0.06905   0.0   2.18  0.0  0.458  7.147     222.0  18.7  396.9    5.33  36.2
 0.02985   0.0   2.18  0.0  0.458  6.43   …  222.0  18.7  394.12   5.21  28.7
 0.08829  12.5   7.87  0.0  0.524  6.012     311.0  15.2  395.6   12.43  22.9
 0.14455  12.5   7.87  0.0  0.524  6.172     311.0  15.2  396.9   19.15  27.1
 0.21124  12.5   7.87  0.0  0.524  5.631     311.0  15.2  386.63  29.93  16.5
 0.17004  12.5   7.87  0.0  0.524  6.004     311.0  15.2  386.71  17.1   18.9
 0.22489  12.5   7.87  0.0  0.524  6.377  …  311.0  15.2  392.52  20.45  15.0
 0.11747  12.5   7.87  0.0  0.524  6.009     311.0  15.2  396.9   13.27  18.9
 0.09378  12.5   7.87  0.0  0.524  5.88

In [40]:
y=data[:,14]
y=reshape(y,(1,506))

1×506 Array{Float64,2}:
 24.0  21.6  34.7  33.4  36.2  28.7  …  16.8  22.4  20.6  23.9  22.0  11.9

In [17]:
x=data[:,1:13]'
reshape(x,(13,506))

13×506 Array{Float64,2}:
   0.00632    0.02731    0.02729  …    0.06076    0.10959    0.04741
  18.0        0.0        0.0           0.0        0.0        0.0    
   2.31       7.07       7.07         11.93      11.93      11.93   
   0.0        0.0        0.0           0.0        0.0        0.0    
   0.538      0.469      0.469         0.573      0.573      0.573  
   6.575      6.421      7.185    …    6.976      6.794      6.03   
  65.2       78.9       61.1          91.0       89.3       80.8    
   4.09       4.9671     4.9671        2.1675     2.3889     2.505  
   1.0        2.0        2.0           1.0        1.0        1.0    
 296.0      242.0      242.0         273.0      273.0      273.0    
  15.3       17.8       17.8      …   21.0       21.0       21.0    
 396.9      396.9      392.83        396.9      393.45     396.9    
   4.98       9.14       4.03          5.64       6.48       7.88   

In [20]:
x_mean=mean(x,2)

13×1 Array{Float64,2}:
   3.61352 
  11.3636  
  11.1368  
   0.06917 
   0.554695
   6.28463 
  68.5749  
   3.79504 
   9.54941 
 408.237   
  18.4555  
 356.674   
  12.6531  

In [21]:
x_std=std(x,2)

13×1 Array{Float64,2}:
   8.60155 
  23.3225  
   6.86035 
   0.253994
   0.115878
   0.702617
  28.1489  
   2.10571 
   8.70726 
 168.537   
   2.16495 
  91.2949  
   7.14106 

In [23]:
x_norm= (x.-x_mean)./x_std

13×506 Array{Float64,2}:
 -0.419367  -0.416927  -0.416929  …  -0.413038  -0.407361  -0.41459 
  0.284548  -0.48724   -0.48724      -0.48724   -0.48724   -0.48724 
 -1.28664   -0.592794  -0.592794      0.115624   0.115624   0.115624
 -0.272329  -0.272329  -0.272329     -0.272329  -0.272329  -0.272329
 -0.144075  -0.73953   -0.73953       0.157968   0.157968   0.157968
  0.413263   0.194082   1.28145   …   0.983986   0.724955  -0.362408
 -0.119895   0.366803  -0.265549      0.796661   0.736268   0.434302
  0.140075   0.556609   0.556609     -0.772919  -0.667776  -0.61264 
 -0.981871  -0.867024  -0.867024     -0.981871  -0.981871  -0.981871
 -0.665949  -0.986353  -0.986353     -0.802418  -0.802418  -0.802418
 -1.45756   -0.302794  -0.302794  …   1.1753     1.1753     1.1753  
  0.440616   0.440616   0.396035      0.440616   0.402826   0.440616
 -1.0745    -0.491953  -1.20753      -0.982076  -0.864446  -0.668397

In [34]:
srand(1)
A=randperm(506)
trn=A[1:400]
tst=A[401:506]

106-element Array{Int64,1}:
 122
 410
 302
 267
  67
 249
 338
 297
 129
 195
 349
  60
 296
   ⋮
  25
 323
 351
 417
 139
 457
 301
 203
 414
 487
 298
 189

In [35]:
xtrn=x_norm[:,trn]

13×400 Array{Float64,2}:
 -0.410443  -0.113706    -0.414262   …  -0.41168    -0.405218   -0.408378 
 -0.48724   -0.48724      1.01346        2.08539    -0.48724    -0.48724  
 -1.26477   -0.180279    -0.740017      -1.37701    -0.375604   -0.164245 
 -0.272329  -0.272329    -0.272329      -0.272329   -0.272329   -0.272329 
 -0.575564  -0.0922961   -1.00792       -1.24006    -0.299411   -0.0664067
 -0.968713  -1.86678     -0.823542   …  -0.570203    0.269515    0.612518 
  0.75403   -1.09329     -1.42723       -1.77893     1.01337     0.462722 
 -0.383311  -0.605802     1.3514         3.28405    -0.64688    -0.53072  
 -0.752178  -0.637331    -0.981871      -0.637331   -0.522484   -0.407638 
 -1.27709   -0.618482    -0.618482       0.0163931  -0.143809    0.140995 
 -0.302794  -0.0256513   -0.718509   …  -0.0718418   1.12911    -0.302794 
  0.37599   -0.068175     0.40907        0.390558    0.422433    0.426267 
  0.185818  -0.00182931  -0.0312367     -0.681      -0.0536423  -0.349117 

In [36]:
xtst=x_norm[:,tst]

13×106 Array{Float64,2}:
 -0.411772   1.25847   -0.41599   …   0.241611  -0.403706  -0.405478 
 -0.48724   -0.48724    0.970582     -0.48724   -0.48724    1.44223  
  2.11552    1.01499   -0.735644      1.01499    0.405697  -1.12192  
 -0.272329  -0.272329  -0.272329     -0.272329  -0.272329  -0.272329 
  0.227006   0.365083  -1.0502        0.244266  -1.01568   -1.01568  
 -0.399413   0.807503   0.434612  …  -0.242855  -0.703988   0.386221 
  0.551536   1.11639   -1.00093       0.398776  -0.375678  -1.40236  
 -0.758719  -1.1063     0.805741     -0.118318   1.1991     0.366459 
 -0.867024   1.6596    -0.292791      1.6596    -0.637331  -0.522484 
 -1.30676    1.52941   -0.470147      1.52941   -0.707483  -0.0607412
  0.297683   0.805778  -1.08803   …   0.805778  -1.13422   -1.50375  
  0.22998   -1.94221    0.428019      0.394392   0.440616   0.286609 
  0.226428   0.998022  -0.44154       0.325853   0.446283  -1.13331  

In [42]:
ytrn=y[:,trn]

1×400 Array{Float64,2}:
 26.4  16.1  17.1  19.0  21.7  17.4  …  23.9  18.3  8.8  18.6  19.8  22.8

In [43]:
ytst=y[:,tst]

1×106 Array{Float64,2}:
 20.3  27.5  22.0  30.7  19.4  24.5  …  24.8  42.3  16.3  19.1  20.3  29.8

In [53]:
weight=randn(1,13)*0.1

1×13 Array{Float64,2}:
 -0.061301  0.0606  0.143596  0.037619  …  -0.178739  0.0381387  -0.143957

In [46]:
predict(w,x)=w*x

predict (generic function with 1 method)

In [54]:
ypred=predict(weight,xtrn)

1×400 Array{Float64,2}:
 -0.247931  -0.426921  0.0652156  …  0.0585327  -0.0505832  0.303362

In [57]:
loss(w,x,y)=sum((y-predict(w,x)).^2)/(2*length(y))

loss (generic function with 1 method)

In [61]:
results=Dict("trainloss"=>loss(weight,xtrn,ytrn),"testloss"=>
loss(weight,xtst,ytst))

Dict{String,Float64} with 2 entries:
  "testloss"  => 293.665
  "trainloss" => 292.529

In [65]:
error=abs(ytrn-ypred)


1×400 Array{Float64,2}:
 26.6479  16.5269  17.0348  19.3128  …  9.88973  18.5415  19.8506  22.4966

In [68]:
sum(error.<sqrt(results["trainloss"]))

106